### PR TITLE
Update README with terraform-docs

### PR DESCRIPTION
**Pull request by ozbillwang**
README update only.

explain in #53

### CODE REVIEW

**Comment by ozbillwang** [comment]
I do nothing for the build failed. This PR is only a README update.

**Review by G-11-P — APPROVED** [review]
Submit

**Review by G-11-P — APPROVED** [review]

**Review by G-11-P — APPROVED** [review]

**Comment by G-11-P** [comment]
merge approve

**Comment by ozbillwang** [comment]
seems this PR has been approved. Who can trigger the buid ?

**Comment by lonegunmanb** [comment]
@ozbillwang Thanks for your contribution and apology for this late reply. We've added a new CI pipeline to this module and now we're using terraform-docs to update readme file, so I'm closing this pr now.

**Pull request closed without merging**
